services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: docusage
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docusage
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docusage"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://docusage:password@db:5432/docusage
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python -c 'import asyncio; from database.db import Database; asyncio.run(Database().init_tables())' &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: